---
global:
  scrape_interval: 15s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    -
      static_configs:
        -
          targets:
            - 0.0.0.0:9093
rule_files:
  - generic-rules.yml
scrape_configs:
  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - 0.0.0.0:9091
  -
    job_name: node_exporter
    static_configs:
      -
        targets:
          - 0.0.0.0:9100
  -
    job_name: substrate_node
    static_configs:
      -
        targets:
          - 0.0.0.0:9615
