---
groups:
-
  name: substrate node
  rules:
  -
    alert: instance down
    expr: up == 0
    for: 1m
    annotations:
      summary: >-
        instance down: $labels.instance
      description: |
        [{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute.
    labels:
      severity: critical
  -
    alert: high cpu load
    expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 0m
    annotations:
      summary: >-
        high cpu load: $labels.instance
      description: |
        cpu load greater than 80%
        value: {{ $value }}
        labels: {{ $labels }}
    labels:
      severity: warning
