---
global:
    resolve_timeout: 1m
route:
    receiver: email-notifications
receivers:
    -
        name: email-notifications
        email_configs:
            -
                to: rob@manta.systems
                from: alert@gallumbits.calamari.systems
                smarthost: email-smtp.us-west-2.amazonaws.com:587
                auth_username: smtp_username
                auth_password: smtp_password
                require_tls: yes
